# Generated by Django 6.1 on 2026-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], max_length=10, verbose_name='Роль'),
        ),
    ]
